[package]
name = "imgui"
version = "0.2.0-pre"
edition = "2018"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>", "imgui-rs contributors"]
description = "High-level Rust bindings to dear imgui"
homepage = "https://github.com/Gekkio/imgui-rs"
repository = "https://github.com/Gekkio/imgui-rs"
license = "MIT/Apache-2.0"
categories = ["gui", "api-bindings"]
readme = "README.markdown"

[badges]
travis-ci = { repository = "Gekkio/imgui-rs" }

[dependencies]
bitflags = "1.0"
glium = { version = "0.25.1", default-features = false, optional = true }
gfx = { version = "0.18", optional = true }
imgui-sys = { version = "0.2.0-pre", path = "imgui-sys" }
lazy_static = "1.1"
parking_lot = "0.8"

[dev-dependencies]
memoffset = "0.4"

[workspace]
members = [
    "imgui-sys",
    "imgui-gfx-renderer",
    "imgui-glium-renderer",
    "imgui-winit-support",
    "imgui-examples",
    "imgui-gfx-examples",
    "imgui-sys-bindgen"
]

[replace]
"glium:0.25.1" = { git = 'https://github.com/kosyak/glium.git', branch = "master" }
"winit:0.20.0-alpha2" = { git = 'https://github.com/kosyak/winit.git', branch = "master" }

